version: "3.9"

services:
  backend:
    build: ./backend
    container_name: brunella-backend
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - QWEN_API_KEY=${QWEN_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - DATABASE_URL=postgresql://brunella:secret@db:5432/agents
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: brunella-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: brunella-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=brunella
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=agents
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: brunella-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
