# Build phase
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY vite.config.ts ./
COPY public ./public
COPY src ./src
COPY index.html ./

RUN npm install
RUN npm run build

# Serve phase
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

COPY --from=build /app/dist .

COPY frontend/nginx.conf /etc/nginx/nginx.conf

ENTRYPOINT ["nginx", "-g", "daemon off;"]
